package presentation;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;

public class AdminView {
    private static AdminView adminView = new AdminView();
    public static AdminView getInstance(){
        return adminView;
    }
    public JFrame framea= new JFrame();
    public JPanel panela = new JPanel();
    public JPanel panel3 = new JPanel();
    public JButton bb = new JButton("Back");
    public JPanel panelm = new JPanel(new GridLayout(2, 2));
    public JButton bm = new JButton("Manage products");
    public JButton bm2 = new JButton("Creare meniu");
    public JButton br2 = new JButton("Generare rapoarte");
    public JButton bl2 = new JButton("Log out");
    public JPanel paneltp2 = new JPanel();
    public JTable tp2= new JTable();
    public JPanel panelm2 = new JPanel();
    JLabel managel= new JLabel("Manage products");
    JPanel panelmb = new JPanel(new GridLayout(2, 2));
    public JButton ba2 = new JButton("Adaugare produs");
    public JButton bi = new JButton("Import produse");
    public JButton br3 = new JButton("Sterge produs");
    public JButton bm4 = new JButton("Modifica produs");
    public JPanel panelcp1 = new JPanel();
    JLabel cpl1 = new JLabel("Adauga comanda");
    JPanel panelid2= new JPanel();
    JLabel idl2 = new JLabel("Id:");
    public JComboBox<Integer> c2 = new JComboBox<>();
    public JTextField cpt = new JTextField("Titlu");
    public JTextField cpp = new JTextField("Pret");
    public JButton bac = new JButton("Adaugare produs");
    public JButton bcreate= new JButton("Pune comanda");
    public JPanel panela3 = new JPanel();
    JLabel addl3= new JLabel("Adaugare produs");
    public JTextField titlut= new JTextField("Titlu");
    public JTextField prett = new JTextField("Pret");
    public JTextField caloriit = new JTextField("Calorii");
    public JTextField proteinet = new JTextField("Proteine");
    public JTextField grasimit= new JTextField("Grasimi");
    public JTextField sodiut = new JTextField("Sodiu");
    public JButton bap1 = new JButton("Adaugare");
    public JPanel panelr3 = new JPanel();
    JLabel stergl = new JLabel("Sterge produs");
    public JTextField stergt = new JTextField("id produs");
    public JButton brp = new JButton("Sterge");
    public JPanel panelmo = new JPanel();
    JLabel modifl= new JLabel("Modifica produs");
    public JTextField modif = new JTextField("Id produs");
    public JTextField modt= new JTextField("Titlu");
    public JTextField modp = new JTextField("Pret");
    public JTextField modc = new JTextField("Calorii");
    public JTextField modpr = new JTextField("Proteine");
    public JTextField modg= new JTextField("Grasimi");
    public JTextField mods = new JTextField("Sodiu");
    public JButton bmp = new JButton("Modifica");
    public JPanel panelre = new JPanel();
    JLabel rel = new JLabel("Generare rapoarte");
    public JTextField cate= new JTextField("de cate ori s-a comandat");
    public JComboBox c3 = new JComboBox();
    public JButton bgr = new JButton("Generare raport");
    public JTextField minp = new JTextField("valoare minimala de comanda");
    public JTextField start = new JTextField("start time");
    public JTextField end = new JTextField("end time");
    public JTextField data= new JTextField("data");
    public AdminView(){
        framea.setTitle("Administrator");
        framea.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        framea.setSize(1000, 600);
        panelm.add(bm);
        panelm.add(bm2);
        panelm.add(br2);
        panelm.add(bl2);
        panelm.setBorder(new EmptyBorder(40, 30, 40, 30));
        managel.setAlignmentX(0.5f);
        panelmb.add(ba2);
        panelmb.add(bi);
        panelmb.add(br3);
        panelmb.add(bm4);
        panelm2.add(managel);
        panelm2.add(panelmb);
        panelm2.setLayout(new BoxLayout(panelm2, BoxLayout.Y_AXIS));
        panelm2.setBorder(new EmptyBorder(40, 30, 40, 30));
        panelm2.setVisible(false);
        addl3.setAlignmentX(0.5f);
        titlut.setColumns(30);
        prett.setColumns(30);
        caloriit.setColumns(30);
        proteinet.setColumns(30);
        grasimit.setColumns(30);
        sodiut.setColumns(30);
        bap1.setAlignmentX(0.5f);
        panela3.add(addl3);
        panela3.add(titlut);
        panela3.add(prett);
        panela3.add(caloriit);
        panela3.add(proteinet);
        panela3.add(grasimit);
        panela3.add(sodiut);
        panela3.add(bap1);
        panela3.setLayout(new BoxLayout(panela3, BoxLayout.Y_AXIS));
        panela3.setVisible(false);
        stergl.setAlignmentX(0.5f);
        stergt.setColumns(30);
        brp.setAlignmentX(0.5f);
        panelr3.add(stergl);
        panelr3.add(stergt);
        panelr3.add(brp);
        panelr3.setLayout(new BoxLayout(panelr3, BoxLayout.Y_AXIS));
        panelr3.setVisible(false);
        modifl.setAlignmentX(0.5f);
        modif.setColumns(30);
        modt.setColumns(30);
        modp.setColumns(30);
        modc.setColumns(30);
        modpr.setColumns(30);
        modg.setColumns(30);
        mods.setColumns(30);
        bmp.setAlignmentX(0.5f);
        panelmo.add(modifl);
        panelmo.add(modif);
        panelmo.add(modt);
        panelmo.add(modp);
        panelmo.add(modc);
        panelmo.add(modpr);
        panelmo.add(modg);
        panelmo.add(mods);
        panelmo.add(bmp);
        panelmo.setLayout(new BoxLayout(panelmo, BoxLayout.Y_AXIS));
        panelmo.setVisible(false);
        cpl1.setAlignmentX(0.5f);
        panelid2.add(idl2);
        panelid2.add(c2);
        cpt.setColumns(30);
        cpp.setColumns(30);
        panelcp1.add(addl3);
        panelcp1.add(panelid2);
        panelcp1.add(bac);
        panelcp1.add(cpt);
        panelcp1.add(cpp);
        panelcp1.add(bcreate);
        panelcp1.setBorder(new EmptyBorder(40, 30, 40, 30));
        panelcp1.setLayout(new BoxLayout(panelcp1, BoxLayout.Y_AXIS));
        panelcp1.setVisible(false);
        rel.setAlignmentX(0.5f);
        cate.setColumns(30);
        minp.setColumns(30);
        start.setColumns(30);
        end.setColumns(30);
        data.setColumns(30);
        panelre.add(rel);
        panelre.add(cate);
        panelre.add(minp);
        panelre.add(start);
        panelre.add(end);
        panelre.add(data);
        panelre.add(c3);
        panelre.add(bgr);
        panelre.setBorder(new EmptyBorder(40, 30, 40, 30));
        panelre.setLayout(new BoxLayout(panelre, BoxLayout.Y_AXIS));
        panelcp1.setVisible(false);
        bb.setAlignmentX(0.5f);
        panel3.add(panelm);
        panel3.add(panelm2);
        panel3.add(panela3);
        panel3.add(panelr3);
        panel3.add(panelmo);
        panel3.add(panelcp1);
        panel3.add(panelre);
        panel3.add(bb);
        panel3.setBorder(new EmptyBorder(20, 0, 20, 0));
        panel3.setLayout(new BoxLayout(panel3, BoxLayout.Y_AXIS));
        panela.add(panel3);
        tp2.setSize(new Dimension(1000, 400));
        paneltp2.add(tp2);
        panela.add(paneltp2);
        framea.add(panela);
        framea.setVisible(true);
    }
}
